### ISSUE TITLE
Client.connect throws a runtime error

### ISSUE THREAD

**Issue by Mishio595** [rethinkdb/rethinkdb-rs#29]
When attempting to open a connection, I receive the following error `ERROR 2018-06-03T21:04:08Z: r2d2: driver`

The only place I can see this being thrown is when I call connect on my client struct. I wasn't able to find much information beyond this due to how vague the error is.

**Comment by rushmorem** [comment]
Is your server running on the default port on `127.0.0.1`? If not, did you specify your details using the `Config` struct? Also, do you have [logging](https://github.com/rethinkdb-rs/reql/blob/217eb104d757e6d0f2e3b568b74212a7b35ab19d/macros/examples/server-status.rs) enabled?

**Comment by Mishio595** [comment]
Verified my DB is runnning locally, bound on `127.0.0.1:28015` its my local testing version so I just use admin with no password, I made a `Config` with ```rs
use reql;
// --snip--
let mut db_config = reql::Config::default();
db_config.db = "name_of_db";```

I also know the settings are right because I can successfully connect with the same setup in both JS and Lua without issues. I have not enabled a logger for reql yet, just the crates `log` and `env_logger`

**Comment by rushmorem** [comment]
If you run the following query in the data explorer, what do you get?

```js
r.db("rethinkdb").table("server_status").getField("network")
```

You should see something like:-

```json
{
"canonical_addresses": [
{
"host":  "127.0.0.1" ,
"port": 29015
} ,
{
"host":  "::1" ,
"port": 29015
}
] ,
"cluster_port": 29015 ,
"connected_to": { } ,
"hostname":  "rushmorem" ,
"http_admin_port": 8080 ,
"reql_port": 28015 ,
"time_connected": Sun Jun 03 2018 08:53:16 GMT+00:00
}
```

**Comment by Mishio595** [comment]
```json

{

    "canonical_addresses": [
        {
            "host": "127.0.0.1" ,
            "port": 29015
        } ,
        {
            "host": "::1" ,
            "port": 29015
        }
    ] ,
    "cluster_port": 29015 ,
    "connected_to": { } ,
    "hostname": "momiji" ,
    "http_admin_port": 8080 ,
    "reql_port": 28015 ,
    "time_connected": Mon Jun 04 2018 01:51:34 GMT+00:00

}
```

**Comment by rushmorem** [comment]
OK, thanks. I just wanted to make that `canonical_addresses` is set because this driver requires it. Kindly clone this repo, then:-

1. `cd` to the `macros` folder
2. run `cargo run --example server-status`

The examples in that folder have logging turned on. The logs generated should point us in the right direction.

**Comment by Mishio595** [comment]
Did that, failed to compile `proc-macro2` with 8 errors. I freshly cloned the repo to `./reql` and did `cd reql/macros` then `cargo run --example server-status`

**Comment by rushmorem** [comment]
Sorry, I forgot to mention that the examples in that folder need the nightly compiler not older than `2018-05-29`. You will need that to use the `args` macro. Try running the minimal example in the top-level folder. Are you able to connect fine? The `reql` crate itself still runs on stable.

**Comment by inv2004** [comment]
everything was fine. I changed nothing. And today I received "driver" error. windows-10

**Comment by rushmorem** [comment]
> Looks like its error! macros from r2d2, and it does throw it to the top and does not affect connections.

Yes, that's right. I have since switched the logger from `slog` to `log`. That error message does indeed come from `r2d2` but everything still works as expected. I don't have time to dig into this right now though.
