### ISSUE TITLE
How to use args! in stable?

### ISSUE THREAD

**Issue by sackery** [rethinkdb/rethinkdb-rs#30]

**Comment by sackery** [comment]
how to convert args!(|doc| doc.has_fields("unread")) to stable code?

**Comment by sackery** [comment]
how to convert args!(|doc| doc.has_fields("unread")) to a string representation?

**Comment by rushmorem** [comment]
The `args` macro is no longer available in latest versions. For closures, use `reql::macros::func`. Your example can be written as 

```rust
func!(|doc| doc.has_fields("unread"))
```

on the latest version.
