### ISSUE TITLE
order_by with desc order #question

### ISSUE THREAD

**Issue by inv2004** [rethinkdb/rethinkdb-rs#35]
Hello,

Is it possible to pass args to order_by to retrieve desc order by index?
Something lik4 r.order_by(index = r.desc('time')) // python

Thank you,

**Comment by rushmorem** [comment]
Yes, it should be possible. Try something like:

```rust
r.db("dbname").table("tablename").order_by(args!{index: r.desc("time")})
```

**Comment by rushmorem** [comment]
On v0.7.0, this can now be written as

```rust
r.db("dbname").table("tablename").order_by(r.index(r.desc("time")))
```
