### ISSUE TITLE
driver client buggy

### ISSUE THREAD

**Issue by charleschege** [rethinkdb/rethinkdb-rs#45]
when trying to update something or replace an entry , I get Driver(Other ("Client is buggy (failed to serialize query.")))

**Comment by zicklag** [comment]
I'm pretty sure that means that you are somehow misusing the library when making a request. Like you are doing something invalid so that it can't create a valid query to send to the server.

**Comment by rushmorem** [comment]
The version for which this issue was opened is now out of date. I've just verified that this is working fine in `v0.7.0`.
