### ISSUE TITLE
The State of the Library: How Can We Help?

### ISSUE THREAD

**Issue by zicklag** [rethinkdb/rethinkdb-rs#47]
Hey there, I have interest in using this library for at least one project and I was curious what kind of things might be available for helping with to get 0.1.0 released. I can see there are a few issues in the 0.1.0 milestone and I was wondering where we are at with those.

It is very possible that I *won't* have time to help, but I *might* get some time so I wanted to get a feel for what the state of the library is right now.

Also, would you advise against using the `next` branch version? I was curious whether it would be worth trying out the updates in the branch or if it isn't at all usable.

**Comment by zicklag** [comment]
Hey @rushmorem, just throwing this out there, but what would you think of adding me as a collaborator on this repo? Me and @opax7 from @katharostech are going to be using this but we needed at least a small updated ( #48 ). If we find the time we would also like to work on improving the documentation and/or getting the next version with async/await support working.

If not, that's perfectly fine and we can just maintain our own fork for the moment and create PRs to merge our changes later.

**Comment by rushmorem** [comment]
> Also, would you advise against using the next branch version? I was curious whether it would be worth trying out the updates in the branch or if it isn't at all usable.

`master` should be usable but I wouldn't recommend using it in production because:-

1. It has a few known bugs and performance issues
2. I don't think the `args` macro still works as it is nightly only

As for the `next` branch, I last worked on it before `async/await` stabilised so it is nightly only and it obviously won't work on latest nightly. Also, it only has a few commands implemented.

> would you think of adding me as a collaborator on this repo?

Sure! Done.

**Comment by zicklag** [comment]
Thanks for the update. And thanks for adding me as a collaborator! Hopefully I'll be able to help out a bit.

RethinkDB is by far my favorite database and Rust is by far my favorite language, so I really want to see this library grow. :slightly_smiling_face:

**Comment by zicklag** [comment]
@rushmorem Do you want to give me access to push crates.io releases, too, or do you want me just to get it ready for release and then you can push it?

I want to do a release with the merge of the last PR, I've just got to bump the version first.

**Comment by rushmorem** [comment]
> Thanks for the update. And thanks for adding me as a collaborator!

It's my pleasure :)

> RethinkDB is by far my favorite database and Rust is by far my favorite language, so I really want to see this library grow

You and me both :)

> Do you want to give me access to push crates.io releases, too

Done
