### ISSUE TITLE
next branch delivery plan

### ISSUE THREAD

**Issue by giacomocariello** [rethinkdb/rethinkdb-rs#51]
I noticed next branch supports futures ^0.3. Is there any plan to release an updated crate with such improvements?

**Comment by zicklag** [comment]
Hi @giacomocariello. Right now that branch doesn't actually compile and needs a lot ( I think ) of work to bring it up-to-date. I want to get it all updated and publish a new release with Futures 0.3 and `async`/`await` support, but I don't know when I will have the time, unfortunately.

I also have hopes of getting it to run on stable Rust by porting the `args!` macro ( the last thing that requires nightly rust, I think ) to use `proc_macro_hack`, but again, I don't know when I will have the time. The interest is definitely there for when I do get the time though. :wink:

**Comment by rushmorem** [comment]
The latest crates are now built on `next` even though it hasn't been merged into main yet.
