### ISSUE TITLE
How to create an index?

### ISSUE THREAD

**Issue by mikekonan** [rethinkdb/rethinkdb-rs#54]
Hello,

I have spent some time but was unsuccessful in figuring out how to specify arguments to create an index.

The particular one I need to create:
```
r.db("registry").table("messages").indexCreate("index", [r.row("last_name"), r.row("first_name")])
```

Appreciate any help:)

**Comment by rushmorem** [comment]
Hello,

I'm sorry the documentation is currently very lacking.

On v0.7.0, this query can be written as

```rust
r.db("registry")
    .table("messages")
    .index_create(r.args(("index", func!(|doc| {
        [doc.clone().get_field("last_name"), doc.get_field("first_name")]
    }))
```

**Comment by rushmorem** [comment]
Starting with v0.8.0, you can drop the closure and write that query as

```rust
r.db("registry").table("messages").index_create(r.args(("index", [r.row("last_name"), r.row("first_name")])))
```
