### ISSUE TITLE
How to connect with non default params

### ISSUE THREAD

**Issue by yabirgb** [rethinkdb/rethinkdb-rs#55]
I've tried to connect with non default params but I can't create a Config object since the `retries` field is private. Also I can't implement a constructor since I'm working outside the crate

```
fn load<'a>(socket: SocketAddr, db: &'a str, port: &'a str, password: &'a str, retries:u64) -> Config<'a> {
    Config {
        servers: vec![socket],
        db: "test",
        user: "admin",
        password: "",
        retries: retries,
        #[cfg(feature = "tls")]
        tls: None,
    }
}
```

Is there something that I'm missing?

**Comment by zicklag** [comment]
It looks like, for the currently released version, you are not allowed to set the retries, but if you just need to be able to create a `Config` object, you can use the `Default` implementation:

```rust
fn load<'a>(socket: SocketAddr, db: &'a str, password: &'a str) -> Config<'a> {
    Config {
        servers: vec![socket],
        db,
        user: "admin",
        password,
        ..Default::default(),
    }
}
```

**Comment by rushmorem** [comment]
`v0.1.0` is now out. See https://docs.rs/reql/0.1.0/reql/struct.r.html#method.connection.
