### ISSUE TITLE
How to correctly use order_by and limit?

### ISSUE THREAD

**Issue by wesleypeeters** [rethinkdb/rethinkdb-rs#59]
Hi.

I'm trying to write a fairly simple query that'll fetch the 2000 latest "records" (new to rethink so excuse me if I'm using incorrect terminology). 

Lack of documentation made composing the query a bit challenging, but I came up with the following:
```
r.db("dbname").table("tablename").order_by(r.desc("time")).filter(reql::func!(|doc| -> reql::Command {
	doc.get_field("time").lt(r.now())
})).limit(2000).run(&session).try_next().await;
```

However, this doesn't compile because `Command::limit` doesn't accept an integer of any kind as a parameter, and `Command::order_by` doesn't accept whatever `r::desc` returns. 

Could anyone provide a working example of how to use these methods? 

Thanks!

**Comment by rushmorem** [comment]
Hi,

Unfortunately, as you discovered here, `order_by` is not fully implemented yet and `limit` is not yet implemented at all.

> Lack of documentation made composing the query a bit challenging

Yeah,  this is a known issue but currently this driver is not yet stable enough to start adding documentation as then we will have to keep changing it as the driver changes. Considering the number of commands RethinkDB has that would be very time consuming and counterproductive.

**Comment by ghost** [comment]
Stumbled over this while looking into using a rust driver for performance,bit's a bit unclear what the status/progress of the library is.

Could it be an idea to add a section to the readme with information on what's missing and/or needs improvements?

**Comment by wesleypeeters** [comment]
Understandable. 

I'll see if I can muster up enough knowledge and courage to start working on the implementation of a couple of the commands I'd need. I (and probably others) would appreciate it if you could mark the existing releases as pre-releases. Perhaps mentioning it in the `readme.md` isn't a bad idea either, so it's at least clear to people that this is an incomplete implementation and they (potential users of the library) don't take it as a "drag n drop" solution while it isn't one (yet). 

Is there some sort of overview with to-do's/commands yet to be implemented so I (and perhaps other members of the community) can get some oversight on the state of the library as a whole?

**Comment by wesleypeeters** [comment]
See #60 for the implementation of `asc`+`desc`, see #61 for implementation of `limit`. Documentation for both is included. Closing in favor of those pr's.

**Comment by rushmorem** [comment]
> Could it be an idea to add a section to the readme with information on what's missing and/or needs improvements?

Yeah. I have been meaning to do this for a while now but so far I just can't find enough time to do so due to pressure at work.

> Is there some sort of overview with to-do's/commands yet to be implemented so I (and perhaps other members of the community) can get some oversight on the state of the library as a whole?

Not yet but it is on my todo list.
