### ISSUE TITLE
How to use filter

### ISSUE THREAD

**Issue by DreamTexX** [rethinkdb/rethinkdb-rs#73]
Is there any docs on how to filter stuff with this lib?

**Comment by taufik-nurhidayat** [comment]
```rust
r.table("table_name").filter(reql::func!(|doc| doc.get_field("field").eq(your_variable)))
```
i'm used that and works, but i don't know how to use `.ne()` command

**Comment by DreamTexX** [comment]
Hey, shortly after posting this I found out about `func!()`. I think I can close this now, thanks! (This should still be documented in my opinion).
