### ISSUE TITLE
Skip Command Args

### ISSUE THREAD

**Issue by taufik-nurhidayat** [rethinkdb/rethinkdb-rs#74]
How i can use skip args?
```rust
r.table("table").limit(10 as isize).skip(25 as isize)
```
nah, that skip can't work and doesn't have implementor like in limit command

**Comment by taufik-nurhidayat** [comment]
No one comment to my issue haha

**Comment by vettich** [comment]
@fiik346 you could try [unreql](https://crates.io/crates/unreql)

**Comment by taufik-nurhidayat** [comment]
Instead use skip, i use greater than command with date field
