### ISSUE TITLE
Eliminate use of threads by creating a better integration with Tokio

### ISSUE THREAD

**Issue by rushmorem** [rethinkdb/rethinkdb-rs#8]

**Comment by Sumrachek** [comment]
Hello! I'm going to use reql in some project and worried by this issue. It is critical for me to process many parallel requests and I don't want to have many threads. My project uses only stable Rust, so I can use only 0.0.26 reql version. Is it possible to fix the issue in 0.0.2x version?

**Comment by rushmorem** [comment]
> I'm going to use reql in some project and worried by this issue. It is critical for me to process many parallel requests and I don't want to have many threads.

This will be resolved in `v0.1.0` which I'm currently working towards in the next branch. I've already eliminated all threads in that branch.

> My project uses only stable Rust, so I can use only 0.0.26 reql version. Is it possible to fix the issue in 0.0.2x version?

Unfortunately, I don't personally have enough time to continue development on the 0.0.2x series. My focus right now is release v0.1.0 as soon as possible. That version will, unfortunately, require nightly Rust as it makes use of async/await features.

**Comment by TotalKrill** [comment]
Looking forward to it!

**Comment by charleschege** [comment]
Do you have a release date in mind?

**Comment by khionu** [comment]
Will this be usable without Tokio? I have my own Executor that I would be using it with.

**Comment by zicklag** [comment]
> That version will, unfortunately, require nightly Rust as it makes use of async/await features.

Will it be able to support stable now with [async being in Rust 1.39](https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html#the-await-is-over,-async-fns-are-here)?

**Comment by zicklag** [comment]
FYI I just found that we still need nightly to use the `args!` macro as it requires the `proc_macro_hygiene` feature.

Related: https://github.com/rethinkdb/rethinkdb-rs/issues/30.

**Comment by rushmorem** [comment]
Latest version, `v0.1.0` no longer uses threads. It is fully async.

> Will this be usable without Tokio? I have my own Executor that I would be using it with.

Yes. See https://docs.rs/reql/0.1.0/reql/index.html#import-the-driver for details.

**Comment by zicklag** [comment]
Yay! Good job getting the release out @rushmorem. The lib's looking more tidy and Rusty. 🙂

**Comment by rushmorem** [comment]
Thanks @zicklag :)
